# Generated by Django 5.0.7 on 2024-07-25 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('placas_transito', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tag',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
