# Generated by Django 5.0.7 on 2024-07-25 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu_Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=70)),
                ('url_or_path', models.CharField(max_length=2048)),
                ('new_page', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Menu link',
                'verbose_name_plural': 'Menu Links',
            },
        ),
    ]
